version: x.x.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Release
install:
- cmd: |
    appveyor DownloadFile https://dot.net/v1/dotnet-install.ps1
    powershell -NoLogo -NoProfile -File dotnet-install.ps1 -Version 3.0.100 -InstallDir "%ProgramFiles%\dotnet" -Architecture x64
    REM To get an updated EXE URL, go to https://visualstudio.microsoft.com/downloads/ -> Tools for VS -> Build Tools for VS
    appveyor DownloadFile https://download.visualstudio.microsoft.com/download/pr/1d102ee6-9263-4353-8676-6430f0cc5998/c0457643c8a80b008250148151a51cb6cc0aa2ccb57316db496628faa9b9a84f/vs_BuildTools.exe
    start /wait vs_BuildTools.exe --quiet --wait --norestart --installPath "C:\vsbuildtools" --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --add Microsoft.VisualStudio.Workload.NetCoreBuildTools
build_script:
- cmd: |
    set PATH=C:\vsbuildtools\MSBuild\Current\Bin\amd64;%PATH%
    build.cmd
test: off
artifacts:
- path: Release/net35
  name: de4dot-net35
- path: publish-netcoreapp2.1
  name: de4dot-netcoreapp2.1
- path: publish-netcoreapp3.0
  name: de4dot-netcoreapp3.0
